// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuFFphuFklT74cdiwla25z9rI2chxnrVg',
    appId: '1:422201565458:web:f6a69084e050c153e313cb',
    messagingSenderId: '422201565458',
    projectId: 'ecommerceapp-35eeb',
    authDomain: 'ecommerceapp-35eeb.firebaseapp.com',
    storageBucket: 'ecommerceapp-35eeb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQCYXbHGLX-mugdGiV6EIzJWoRoX5OfCY',
    appId: '1:422201565458:android:e92f9ba7c9e1d402e313cb',
    messagingSenderId: '422201565458',
    projectId: 'ecommerceapp-35eeb',
    storageBucket: 'ecommerceapp-35eeb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoNPzc9xUDCPz1y5fukdZk_A2lL6n2V24',
    appId: '1:422201565458:ios:7ad49424ca637f8be313cb',
    messagingSenderId: '422201565458',
    projectId: 'ecommerceapp-35eeb',
    storageBucket: 'ecommerceapp-35eeb.firebasestorage.app',
    androidClientId: '422201565458-hk4178surkst01rijf2c9l5b5h8p233o.apps.googleusercontent.com',
    iosClientId: '422201565458-2ind3t8ta49e85u6vigj8ae95k2i7443.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuFFphuFklT74cdiwla25z9rI2chxnrVg',
    appId: '1:422201565458:web:e29d24b1d71eacb3e313cb',
    messagingSenderId: '422201565458',
    projectId: 'ecommerceapp-35eeb',
    authDomain: 'ecommerceapp-35eeb.firebaseapp.com',
    storageBucket: 'ecommerceapp-35eeb.firebasestorage.app',
  );

}